global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ai-conductor-backend'
    static_configs:
      - targets: ['ai-conductor-backend-service:3001']
    metrics_path: '/api/metrics'
    scrape_interval: 5s

  - job_name: 'ai-conductor-frontend'
    static_configs:
      - targets: ['ai-conductor-frontend-service:80']
    metrics_path: '/metrics'

  - job_name: 'n8n'
    static_configs:
      - targets: ['ai-conductor-n8n-service:5678']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-service:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-service:6379']
