version: '3.8'

services:
  frontend:
    build:
      context: ./ai-development-conductor/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./ai-development-conductor/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./ai-development-conductor/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - .env
    volumes:
      - ./ai-development-conductor/backend:/app
      - /app/node_modules
