apiVersion: v1
kind: Namespace
metadata:
  name: ai-conductor
  labels:
    name: ai-conductor
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-conductor-quota
  namespace: ai-conductor
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "10"
